FROM registry.access.redhat.com/ubi8/openjdk-17-runtime@sha256:1a40771ffd18a688a4492f319814af5d2e3377eb293c69ca682f29a3a86635ab

RUN mkdir /minecraft

WORKDIR /minecraft

COPY eula.txt /minecraft/eula.txt
COPY server.jar /minecraft/

CMD ["java", "-jar", "server.jar"]
